version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - '5008:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build: ./frontend
    ports:
      - '8081:80' # Portu 8081'e Ã§ekelim (5173 bazen cache'li kalabiliyor)
    restart: always
    depends_on:
      - api
